### ISSUE TITLE
Make entire response object available in load callback

### ISSUE THREAD

**Issue by natoverse** [atsid/circuits-js#9]
Currently circuits unwraps the main data payload from a response JSON object, and sends it as the first argument to the load/success callback. The second argument gets an object with all of the params, the request, etc. We treat hypermedia links specially, and include them in this second argument as well. However, not all service APIs will have one main payload field on the response, and may want access to these secondary ones (just like "links", but not as a magic property). While it is very convenient to simply get the main payload as the first arg, leaving others unavailable is not desirable. We should add a "response" property to this second argument (to match the "request), so the raw data can be accessed.

Note that it is currently possible to work around this issue by using a "response" type plugin to gain access to the raw data during the lifecycle. This issue is primarily to make this more convenient so it is all available in the same callback.

**Comment by natoverse** [comment]
More background on this:

When you call a service method via circuits, you get a very specific set of items passed to your callback. This was originally done to hide some of the ajax complexity, but we've found that there are cases where you will want access to the raw data, and having to wait for us to update the library design isn't useful. So there should be a mechanism where more data is passed to the callback.

Calling a circuits method looks something like:
```
var service = factory.getServiceByName('MyService');
//assuming the schema has a 'readDocument' method, which returns JSON like:
{
    "data": {
        "id": 1,
        "text": "hi"
    },
    "links": [{
        "rel": "self",
        "href": "documents/1"
    }]
}
service.readDocument({
    id: 1
}, {
    success: function (document, args) {
        //The first argument, 'document', contains only the unwrapped portion from the 'data' field:
        console.log('got document: ' + document.id); // "got document 1"

        //The second argument, 'args', contains a bunch of stuff we've packed on, including the original params, the request, links array, and so on. 
        console.log(args); // { id: 1, links: [...], plugin: {...}, request: {...}
    }
});
```
The 'args' param in the success callback should include a `response` field that contains the raw JSON.

**Comment by wastevus** [comment]
So, in the exampe presented, we should have:
```
args.response = {
    "data": {
        "id": 1,
        "text": "hi"
    },
    "links": [{
        "rel": "self",
        "href": "documents/1"
    }]
        
```
am I right?

**Comment by natoverse** [comment]
Yes
